# Generated by Django 4.0 on 2023-04-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_alter_interest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
