# Generated by Django 4.0 on 2023-04-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0003_requests_sender_alter_requests_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chat.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to='auth.user'),
            preserve_default=False,
        ),
    ]
