# Generated by Django 4.0 on 2023-04-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
